Make XXHash the default hash function
NVIDIA/cuCollections pull request #318
Opened 2023-06-14 13:44 UTC by sleeepyjack

This PR introduces `xxhash_32` as the new default hash function for cuco's data structure.

Additional changes:

- Add `cuco::default_hash_function` alias for convenience.
- Default Double Hashing's second hash function: `typename Hash2 = Hash1` for convenience.

2023-06-14 23:20 UTC, PointKernel requested changes
@sleeepyjack can you please hold until #314 is merged?

Also, it would be great to include benchmark comparisons for at least `static_set` to support this change.

2023-06-14 23:20 UTC, PointKernel commented on include/cuco/probe_sequences.cuh
> +template <uint32_t CGSize, typename Hash1, typename Hash2 = Hash1>
I hesitated at first glance then find it's actually not a bad idea.

2023-06-28 16:18 UTC, sleeepyjack commented
It was a bit difficult to get robust benchmark results (see NVIDIA/nvbench#135)
but here are the benchmark results for `cuco::experimental::static_map<int, int>::contains_async`, measuring speedup of xxHash over MurmurHash3 using the minimum runtime as the underlying metric.
| Table size | 6.4MB  | 64MB  | 640MB | 6400MB |
|------------|--------|-------|-------|--------|
| Speedup    | 18.75% | 8.57% | 0.99% | 0.08%  |

2023-06-28 18:01 UTC, PointKernel approved these changes
LGTM!

@sleeepyjack The PR is ready to go once the merge conflict is resolved.

2023-06-29 14:59 UTC, merged