Fix bugs in `insert_and_find`
NVIDIA/cuCollections pull request #389
Opened 2023-11-07 22:57 UTC by PointKernel

TBD

2023-11-08 12:09 UTC, sleeepyjack commented
Gnaaaahhh GH mobile UI tricked me again...I accidentally marked this as ready for review and now I can't undo that on mobile. 🫠

2023-11-09 00:34 UTC, sleeepyjack commented
Proposed spin wait approach: https://godbolt.org/z/hfGxoh9h8

2023-11-10 00:53 UTC, sleeepyjack commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +              cuda::atomic<mapped_type, cuda::thread_scope_device>{(window_ptr + i)->second};
`cuda::atomic_ref`, not `cuda::atomic`

2023-11-10 01:04 UTC, PointKernel commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +              cuda::atomic<mapped_type, cuda::thread_scope_device>{(window_ptr + i)->second};
bug of this year.

2023-11-16 21:02 UTC, sleeepyjack requested changes

2023-11-16 21:02 UTC, sleeepyjack commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +                  "insert_and_find is not supported for unpackable data on pre-Volta GPUs.");
```suggestion
                  "insert_and_find is not supported for pair types larger than 8 bytes on pre-Volta GPUs.");
```

"packable data" sounds misleading.

2023-11-16 21:02 UTC, sleeepyjack commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +              auto const expected_payload = this->empty_slot_sentinel_.second;
```suggestion
```

This is never used.

2023-11-16 21:02 UTC, sleeepyjack commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +              return res;
```suggestion
              return cas_dependent_write(window_ptr + i, window_slots[i], value);
```

2023-11-16 21:02 UTC, sleeepyjack commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +    // independent thread scheduling introduced with the Volta architecture.
Good catch! That wasn't on my radar.

2023-11-16 21:02 UTC, sleeepyjack commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +        if (group.thread_rank() == src_lane) {
I think all threads in the group need to spin wait on the payload. Or alternatively one rank waits and then a subsequent call to `group.sync()`.

2023-11-16 21:02 UTC, sleeepyjack commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +    auto const expected_payload = expected.second;
```suggestion
```
I might be blind but I don't see this variable being used anywhere.

2023-11-16 21:02 UTC, sleeepyjack commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +    // TODO exponential backoff strategy
On my TODO list

2023-11-16 22:19 UTC, PointKernel commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +        if (group.thread_rank() == src_lane) {
`n` threads in a group call the spin will cause at least `n` sequential memory load which would be really bad for performance.

2023-11-16 22:20 UTC, PointKernel commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +        if (group.thread_rank() == src_lane) {
but good point on the group sync

2023-11-16 22:29 UTC, PointKernel commented
/ok to test

2023-11-17 01:32 UTC, PointKernel commented
How come the changes unrelated to `erase` failed an erase test? :sob:

2023-11-17 02:54 UTC, sleeepyjack commented
> How come the changes unrelated to `erase` failed an erase test? 😭

I've seen the erased test spuriously fail in the past. Seems flaky… which means there might be a hidden race condition or something akin.

2023-11-17 21:09 UTC, PointKernel commented
> > How come the changes unrelated to `erase` failed an erase test? 😭
> 
> I've seen the `erase` test spuriously fail in the past. Seems flaky… which means there might be a hidden race condition or something akin.

Looking into this. Would be a separate PR though.

2023-11-17 23:07 UTC, sleeepyjack approved these changes

2023-11-18 00:02 UTC, merged