Use invoke_one when possible
NVIDIA/cuCollections pull request #448
Opened 2024-03-21 21:08 UTC by PointKernel

This PR updates new open addressing implementations to use `cg::invoke_one` when possible.

It doesn't change legacy implementations like multimap or dynamic map, etc.

2024-03-22 02:52 UTC, sleeepyjack approved these changes
Looks good. Shall I run some benchmarks comparing perf on H100?

2024-03-22 04:36 UTC, PointKernel commented
> Looks good. Shall I run some benchmarks comparing perf on H100?

Please do. I expect a maximum difference of 0.5 to 1% runtime difference.

2024-03-22 14:19 UTC, sleeepyjack commented
🙅 Something's not right:

```
nvbench_compare.py dev_baseline.json invoke_one.json
['dev_baseline.json', 'invoke_one.json']
# static_set_contains_unique_occupancy

## [0] NVIDIA H100 PCIe

|  Key  |  Distribution  |  Occupancy  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |       Diff |   %Diff |  Status  |
|-------|----------------|-------------|------------|-------------|------------|-------------|------------|---------|----------|
|  I32  |     UNIQUE     |     0.1     |   6.664 ms |       0.02% |   6.861 ms |       0.01% | 197.133 us |   2.96% |   FAIL   |
|  I32  |     UNIQUE     |     0.2     |   6.654 ms |       0.01% |   7.008 ms |       1.45% | 354.352 us |   5.33% |   FAIL   |
|  I32  |     UNIQUE     |     0.3     |   6.712 ms |       0.01% |   7.108 ms |       0.93% | 395.841 us |   5.90% |   FAIL   |
|  I32  |     UNIQUE     |     0.4     |   6.900 ms |       0.22% |   7.386 ms |       1.29% | 486.485 us |   7.05% |   FAIL   |
|  I32  |     UNIQUE     |     0.5     |   7.246 ms |       0.30% |   7.728 ms |       0.76% | 482.108 us |   6.65% |   FAIL   |
|  I32  |     UNIQUE     |     0.6     |   7.842 ms |       0.36% |   8.487 ms |       1.21% | 644.551 us |   8.22% |   FAIL   |
|  I32  |     UNIQUE     |     0.7     |   8.845 ms |       0.32% |   9.441 ms |       0.65% | 596.367 us |   6.74% |   FAIL   |
|  I32  |     UNIQUE     |     0.8     |  10.837 ms |       0.24% |  11.674 ms |       0.91% | 837.088 us |   7.72% |   FAIL   |
|  I32  |     UNIQUE     |     0.9     |  16.634 ms |       0.02% |  17.461 ms |       0.78% | 826.831 us |   4.97% |   FAIL   |
|  I64  |     UNIQUE     |     0.1     |   7.186 ms |       0.01% |   7.452 ms |       0.57% | 266.888 us |   3.71% |   FAIL   |
|  I64  |     UNIQUE     |     0.2     |   7.276 ms |       2.25% |   7.549 ms |       1.54% | 273.354 us |   3.76% |   FAIL   |
|  I64  |     UNIQUE     |     0.3     |   7.271 ms |       0.11% |   7.614 ms |       0.81% | 343.303 us |   4.72% |   FAIL   |
|  I64  |     UNIQUE     |     0.4     |   7.470 ms |       0.30% |   7.866 ms |       1.05% | 396.046 us |   5.30% |   FAIL   |
|  I64  |     UNIQUE     |     0.5     |   7.832 ms |       0.36% |   8.298 ms |       0.94% | 465.416 us |   5.94% |   FAIL   |
|  I64  |     UNIQUE     |     0.6     |   8.467 ms |       0.40% |   9.011 ms |       1.13% | 544.171 us |   6.43% |   FAIL   |
|  I64  |     UNIQUE     |     0.7     |   9.544 ms |       0.27% |  10.124 ms |       0.79% | 579.527 us |   6.07% |   FAIL   |
|  I64  |     UNIQUE     |     0.8     |  11.669 ms |       0.02% |  12.375 ms |       0.90% | 706.240 us |   6.05% |   FAIL   |
|  I64  |     UNIQUE     |     0.9     |  17.891 ms |       0.01% |  18.606 ms |       0.52% | 714.458 us |   3.99% |   FAIL   |

# static_set_contains_unique_matching_rate

## [0] NVIDIA H100 PCIe

|  Key  |  Distribution  |  MatchingRate  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |       Diff |   %Diff |  Status  |
|-------|----------------|----------------|------------|-------------|------------|-------------|------------|---------|----------|
|  I32  |     UNIQUE     |      0.1       |   7.620 ms |       0.01% |   8.306 ms |       1.20% | 685.944 us |   9.00% |   FAIL   |
|  I32  |     UNIQUE     |      0.2       |   7.602 ms |       0.65% |   8.172 ms |       0.94% | 569.350 us |   7.49% |   FAIL   |
|  I32  |     UNIQUE     |      0.3       |   7.451 ms |       0.30% |   8.103 ms |       1.08% | 652.094 us |   8.75% |   FAIL   |
|  I32  |     UNIQUE     |      0.4       |   7.398 ms |       0.59% |   7.958 ms |       1.08% | 560.744 us |   7.58% |   FAIL   |
|  I32  |     UNIQUE     |      0.5       |   7.257 ms |       0.44% |   7.833 ms |       0.90% | 576.493 us |   7.94% |   FAIL   |
|  I32  |     UNIQUE     |      0.6       |   7.173 ms |       0.49% |   7.678 ms |       1.04% | 504.596 us |   7.03% |   FAIL   |
|  I32  |     UNIQUE     |      0.7       |   7.041 ms |       0.40% |   7.538 ms |       0.85% | 497.576 us |   7.07% |   FAIL   |
|  I32  |     UNIQUE     |      0.8       |   6.933 ms |       0.37% |   7.373 ms |       0.92% | 439.525 us |   6.34% |   FAIL   |
|  I32  |     UNIQUE     |      0.9       |   6.793 ms |       0.24% |   7.176 ms |       0.74% | 383.007 us |   5.64% |   FAIL   |
|  I32  |     UNIQUE     |       1        |   6.671 ms |       0.16% |   6.982 ms |       0.70% | 310.772 us |   4.66% |   FAIL   |
|  I64  |     UNIQUE     |      0.1       |   8.265 ms |       0.57% |   8.853 ms |       1.08% | 587.467 us |   7.11% |   FAIL   |
|  I64  |     UNIQUE     |      0.2       |   8.174 ms |       0.51% |   8.752 ms |       1.08% | 578.102 us |   7.07% |   FAIL   |
|  I64  |     UNIQUE     |      0.3       |   8.068 ms |       0.54% |   8.648 ms |       1.06% | 580.303 us |   7.19% |   FAIL   |
|  I64  |     UNIQUE     |      0.4       |   7.967 ms |       0.45% |   8.502 ms |       1.16% | 534.691 us |   6.71% |   FAIL   |
|  I64  |     UNIQUE     |      0.5       |   7.852 ms |       0.43% |   8.377 ms |       1.10% | 525.209 us |   6.69% |   FAIL   |
|  I64  |     UNIQUE     |      0.6       |   7.748 ms |       0.38% |   8.231 ms |       1.23% | 482.689 us |   6.23% |   FAIL   |
|  I64  |     UNIQUE     |      0.7       |   7.630 ms |       0.34% |   8.055 ms |       0.97% | 424.666 us |   5.57% |   FAIL   |
|  I64  |     UNIQUE     |      0.8       |   7.513 ms |       0.27% |   7.897 ms |       0.97% | 383.988 us |   5.11% |   FAIL   |
|  I64  |     UNIQUE     |      0.9       |   7.393 ms |       0.20% |   7.691 ms |       0.69% | 297.481 us |   4.02% |   FAIL   |
|  I64  |     UNIQUE     |       1        |   7.280 ms |       0.11% |   7.502 ms |       0.61% | 222.233 us |   3.05% |   FAIL   |

# static_set_constains_unique_capacity

## [0] NVIDIA H100 PCIe

|  Key  |  Distribution  |  NumInputs  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |       Diff |   %Diff |  Status  |
|-------|----------------|-------------|------------|-------------|------------|-------------|------------|---------|----------|
|  I32  |     UNIQUE     |    8000     |  14.185 us |       3.03% |  14.986 us |       2.69% |   0.801 us |   5.65% |   FAIL   |
|  I32  |     UNIQUE     |    80000    |  17.819 us |       2.32% |  18.827 us |       2.12% |   1.008 us |   5.66% |   FAIL   |
|  I32  |     UNIQUE     |   800000    |  55.041 us |       0.78% |  60.526 us |       0.67% |   5.485 us |   9.97% |   FAIL   |
|  I32  |     UNIQUE     |   8000000   | 507.201 us |       0.15% | 577.336 us |       2.67% |  70.135 us |  13.83% |   FAIL   |
|  I32  |     UNIQUE     |  80000000   |   5.816 ms |       0.50% |   7.297 ms |       9.96% |   1.481 ms |  25.46% |   FAIL   |
|  I64  |     UNIQUE     |    8000     |  13.554 us |       2.92% |  15.237 us |       5.60% |   1.684 us |  12.42% |   FAIL   |
|  I64  |     UNIQUE     |    80000    |  18.511 us |       2.28% |  19.172 us |       2.08% |   0.662 us |   3.57% |   FAIL   |
|  I64  |     UNIQUE     |   800000    |  60.189 us |       0.79% |  70.294 us |       2.65% |  10.105 us |  16.79% |   FAIL   |
|  I64  |     UNIQUE     |   8000000   | 582.640 us |       0.08% | 734.002 us |       1.92% | 151.362 us |  25.98% |   FAIL   |
|  I64  |     UNIQUE     |  80000000   |   6.292 ms |       0.50% |   9.601 ms |       4.59% |   3.309 ms |  52.59% |   FAIL   |

# static_set_find_unique_occupancy

## [0] NVIDIA H100 PCIe

|  Key  |  Distribution  |  Occupancy  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |     Diff |   %Diff |  Status  |
|-------|----------------|-------------|------------|-------------|------------|-------------|----------|---------|----------|
|  I32  |     UNIQUE     |     0.1     |   7.095 ms |       0.09% |  11.024 ms |       2.16% | 3.929 ms |  55.38% |   FAIL   |
|  I32  |     UNIQUE     |     0.2     |   7.133 ms |       0.69% |  11.091 ms |       2.76% | 3.958 ms |  55.49% |   FAIL   |
|  I32  |     UNIQUE     |     0.3     |   7.242 ms |       0.45% |  11.4 [...]

2024-03-22 17:08 UTC, PointKernel commented
About 50% slower for `find` :scream:

2024-03-23 02:07 UTC, sleeepyjack requested changes
Not sure if the perf regression is worth investigating. If we can create a minimal repro we can ping our CG devs. I'm also ok with shelving the PR for now.

2024-03-25 19:06 UTC, PointKernel commented
I cannot reproduce the performance regression with my local RTX8000:
```
# static_set_find_unique_occupancy

## [0] Quadro RTX 8000

|  Key  |  Distribution  |  Occupancy  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |       Diff |   %Diff |  Status  |
|-------|----------------|-------------|------------|-------------|------------|-------------|------------|---------|----------|
|  I32  |     UNIQUE     |     0.1     |  31.941 ms |       0.28% |  31.925 ms |       0.14% | -16.024 us |  -0.05% |   PASS   |
|  I32  |     UNIQUE     |     0.2     |  31.934 ms |       0.01% |  31.939 ms |       0.02% |   4.440 us |   0.01% |   FAIL   |
|  I32  |     UNIQUE     |     0.3     |  32.245 ms |       0.01% |  32.242 ms |       0.01% |  -2.355 us |  -0.01% |   PASS   |
|  I32  |     UNIQUE     |     0.4     |  33.012 ms |       0.02% |  33.002 ms |       0.01% | -10.054 us |  -0.03% |   FAIL   |
|  I32  |     UNIQUE     |     0.5     |  34.432 ms |       0.02% |  34.449 ms |       0.01% |  16.904 us |   0.05% |   FAIL   |
|  I32  |     UNIQUE     |     0.6     |  36.910 ms |       0.01% |  36.915 ms |       0.01% |   4.985 us |   0.01% |   FAIL   |
|  I32  |     UNIQUE     |     0.7     |  41.218 ms |       0.01% |  41.223 ms |       0.02% |   5.061 us |   0.01% |   FAIL   |
|  I32  |     UNIQUE     |     0.8     |  49.906 ms |       0.01% |  49.917 ms |       0.01% |  11.477 us |   0.02% |   FAIL   |
|  I32  |     UNIQUE     |     0.9     |  75.340 ms |       0.02% |  75.365 ms |       0.04% |  24.811 us |   0.03% |   FAIL   |
|  I64  |     UNIQUE     |     0.1     |  33.937 ms |       0.01% |  33.950 ms |       0.01% |  12.970 us |   0.04% |   FAIL   |
|  I64  |     UNIQUE     |     0.2     |  34.052 ms |       0.02% |  34.045 ms |       0.01% |  -7.124 us |  -0.02% |   FAIL   |
|  I64  |     UNIQUE     |     0.3     |  34.408 ms |       0.02% |  34.429 ms |       0.01% |  21.481 us |   0.06% |   FAIL   |
|  I64  |     UNIQUE     |     0.4     |  35.258 ms |       0.02% |  35.275 ms |       0.02% |  17.199 us |   0.05% |   FAIL   |
|  I64  |     UNIQUE     |     0.5     |  36.791 ms |       0.01% |  36.802 ms |       0.01% |  11.845 us |   0.03% |   FAIL   |
|  I64  |     UNIQUE     |     0.6     |  39.389 ms |       0.02% |  39.397 ms |       0.01% |   8.795 us |   0.02% |   FAIL   |
|  I64  |     UNIQUE     |     0.7     |  43.888 ms |       0.01% |  43.890 ms |       0.01% |   2.224 us |   0.01% |   PASS   |
|  I64  |     UNIQUE     |     0.8     |  52.894 ms |       0.02% |  52.914 ms |       0.01% |  20.027 us |   0.04% |   FAIL   |
|  I64  |     UNIQUE     |     0.9     |  79.321 ms |       0.02% |  79.380 ms |       0.04% |  59.164 us |   0.07% |   FAIL   |
```

Could this issue be H100-specific?

2024-03-26 03:04 UTC, sleeepyjack commented
That's expected. On SM90 the function will use the `ELECT` instruction. Let me collect some profiles so we can investigate what's going on.

2024-05-16 00:39 UTC, sleeepyjack commented
Update: I ran the same exact benchmarks on another H100 node (CTK 12.3) today and wasn't able to verify the regression I initially reported. Will run another test on a different node and report back.

2024-05-28 22:51 UTC, PointKernel commented
@sleeepyjack Any updates on H100 perf results?

2024-05-29 16:15 UTC, sleeepyjack commented on include/cuco/detail/static_set/kernels.cuh
> +#endif
For context: This is the section I've been focussing on in my investigation.

2024-05-29 16:16 UTC, sleeepyjack commented
I tested another H100 HBM3 node with CTK 12.3 and the performance regression is still present although much less pronounced (around 5-6% less throughput).

The instruction diff between the baseline and this version is straightforward:
The baseline
```cpp
if (tile.thread_rank() == 0) {...}
```
compiles to
```
ISETP.NE.AND P0, PT, R7, RZ, PT
```
which stores the leader ID in the `P0` register.

The `cg::invoke_one` version translates to
```
IMAD.MOV.U32 R15, RZ, RZ, 0xf
BSSY B0, 0x7f8f8ec57d60
SHF.L.U32 R15, R15, R8, RZ
WARPSYNC.EXCLUSIVE R15
ELECT P0, URZ, ~URZ
BSYNC B0
```

Compared to the baseline, the new version additionally computes the mask of participating threads (`SHF`) which is then used to synchronize these threads (`WARPSYNC`) before electing a leader (`ELECT`).

I have some profiles which I will share via Slack since I had to use an internal toolchain.

2026-06-10 18:59 UTC, PointKernel commented
Updates: Based on the offline discussion, this issue is fixed for CTK 13.2 or newer.

2026-06-10 18:59 UTC, closed without merging

2026-06-10 20:05 UTC, mhaseeb123 commented
@PointKernel If the issue is fixed, shouldn't we merge this PR with a fresh benchmark, though not sure if we need the `CUCO_HAS_INVOKE_ONE` anymore?

2026-06-10 20:59 UTC, PointKernel commented
> @PointKernel If the issue is fixed, shouldn't we merge this PR with a fresh benchmark, though not sure if we need the `CUCO_HAS_INVOKE_ONE` anymore?

@mhaseeb123 The performance regression is significant, and the underlying issue is only fixed in very recent CTK releases. As a result, I don't think adopting this broadly is justified right now.

With that, applying it to non-performance-critical parts of cudf makes sense from a readability standpoint, since the impact there is negligible. For hot paths, though, I don't think it's worth the cost until our oldest supported CTK is 13.2 or later.

2026-06-10 22:04 UTC, mhaseeb123 commented
Thanks for clarifying