Replace custom atomic operations with cuda atomic operations
NVIDIA/cuCollections pull request #531
Opened 2024-07-06 03:58 UTC by srinivasyadav18

The current cuco implementations use custom atomic functions due to a performance regression with cuda::atomic_ref (https://github.com/NVIDIA/cccl/issues/1008). 

This PR replaces the custom atomic operations with cuda `atomic_ref` operations.

2024-07-06 04:13 UTC, PointKernel commented
/ok to test

2024-07-06 04:17 UTC, PointKernel commented
@srinivasyadav18 wow, you move so fast, thank you! 

Can you please check #469 to address all use cases mentioned there?

2024-07-06 18:00 UTC, PointKernel requested changes
One question about back to back CAS otherwise looks great.

@srinivasyadav18 Can you please compare the performance before and with the current PR to make sure the performance regression of `atomic_ref` is gone?

2024-07-06 18:00 UTC, PointKernel commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> +    using mapped_type = cuda::std::decay_t<decltype(this->empty_value_sentinel())>;
Nice, I didn't pay attention to this.

2024-07-06 18:00 UTC, PointKernel commented on include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
> -      }
Imagine a situation where the key won the CAS while the payload lost. I think we still need this while loop waiting for payload to be in place.

2024-07-08 18:50 UTC, srinivasyadav18 commented
> Can you please compare the performance before

There not any major suprises. Performance remains same! 

For more results :  look at this [gist](https://gist.github.com/srinivasyadav18/7dfc83e989d8a9bb8d574b98693bb872)
# Benchmark Results

## static_map_insert_uniform_multiplicity (with atomic_ref + back2backcas fixes)

### [0] Tesla T4

| Key | Value | Distribution | Multiplicity | Samples |  CPU Time  | Noise |  GPU Time  | Noise |  Elem/s  |
|-----|-------|--------------|--------------|---------|------------|-------|------------|-------|----------|
| I32 |   I32 |      UNIFORM |            1 |     11x | 137.210 ms | 2.44% | 137.201 ms | 2.44% | 728.856M |
| I32 |   I32 |      UNIFORM |            2 |     11x |  98.745 ms | 1.72% |  98.738 ms | 1.72% |   1.013G |
| I32 |   I32 |      UNIFORM |            4 |     11x |  80.823 ms | 2.13% |  80.813 ms | 2.13% |   1.237G |
| I32 |   I32 |      UNIFORM |            8 |     11x |  72.899 ms | 1.53% |  72.892 ms | 1.53% |   1.372G |
| I32 |   I32 |      UNIFORM |           16 |     11x |  67.407 ms | 1.60% |  67.397 ms | 1.60% |   1.484G |
| I64 |   I64 |      UNIFORM |            1 |     11x | 147.886 ms | 2.69% | 147.876 ms | 2.69% | 676.241M |
| I64 |   I64 |      UNIFORM |            2 |     11x | 113.360 ms | 3.36% | 113.353 ms | 3.36% | 882.203M |
| I64 |   I64 |      UNIFORM |            4 |     11x |  94.160 ms | 2.85% |  94.152 ms | 2.85% |   1.062G |
| I64 |   I64 |      UNIFORM |            8 |     11x |  85.379 ms | 2.46% |  85.373 ms | 2.46% |   1.171G |
| I64 |   I64 |      UNIFORM |           16 |     11x |  80.418 ms | 4.49% |  80.411 ms | 4.49% |   1.244G |

## static_map_insert_uniform_multiplicity (with_atomic_ref) 

| Key | Value | Distribution | Multiplicity | Samples |  CPU Time  | Noise |  GPU Time  | Noise |  Elem/s  |
|-----|-------|--------------|--------------|---------|------------|-------|------------|-------|----------|
| I32 |   I32 |      UNIFORM |            1 |     11x | 138.278 ms | 2.23% | 138.271 ms | 2.23% | 723.215M |
| I32 |   I32 |      UNIFORM |            2 |     11x |  99.544 ms | 0.06% |  99.538 ms | 0.06% |   1.005G |
| I32 |   I32 |      UNIFORM |            4 |     11x |  81.622 ms | 0.06% |  81.616 ms | 0.06% |   1.225G |
| I32 |   I32 |      UNIFORM |            8 |     11x |  73.291 ms | 0.05% |  73.285 ms | 0.05% |   1.365G |
| I32 |   I32 |      UNIFORM |           16 |     11x |  67.780 ms | 0.02% |  67.775 ms | 0.02% |   1.475G |
| I64 |   I64 |      UNIFORM |            1 |     11x | 149.755 ms | 0.02% | 149.748 ms | 0.02% | 667.787M |
| I64 |   I64 |      UNIFORM |            2 |     11x | 113.368 ms | 0.03% | 113.361 ms | 0.03% | 882.136M |
| I64 |   I64 |      UNIFORM |            4 |     11x |  95.021 ms | 0.03% |  95.016 ms | 0.03% |   1.052G |
| I64 |   I64 |      UNIFORM |            8 |     11x |  86.188 ms | 0.04% |  86.180 ms | 0.03% |   1.160G |
| I64 |   I64 |      UNIFORM |           16 |     11x |  82.121 ms | 0.04% |  82.116 ms | 0.04% |   1.218G |

2024-07-09 22:47 UTC, sleeepyjack commented
/ok to test

2024-07-11 22:19 UTC, PointKernel commented
/ok to test

2024-07-12 00:25 UTC, PointKernel approved these changes
LGTM

2024-07-12 03:58 UTC, sleeepyjack approved these changes
Same here. Lets merge this puppy.

2024-07-12 04:41 UTC, merged